# This file automatically generated from a template. That's why it defines the world one at a time instead of using loops
import display
import world

from objects import world_object
from objects.General import portal

def generate():
    world.objects.clear()
    world.map = [[ [display.GREEN, display.BLACK, ';', True] for y in range(world.WORLD_Y)] for x in range(world.WORLD_X)]
    world.objects.append(world_object.world_object(portal.update, portal.collide, portal.char, portal.color, portal.type, 25,8,{"newmap": "town", "locx": 0, "locy": 10, "used" : False}))

    world.map[22][5] =  [display.WHITE, display.BLACK, '#', False]
    world.map[23][5] =  [display.WHITE, display.BLACK, '#', False]
    world.map[24][5] =  [display.WHITE, display.BLACK, '#', False]
    world.map[25][5] =  [display.WHITE, display.BLACK, '#', False]
    world.map[26][5] =  [display.WHITE, display.BLACK, '#', False]
    world.map[27][5] =  [display.WHITE, display.BLACK, '#', False]
    world.map[28][5] =  [display.WHITE, display.BLACK, '#', False]
    world.map[22][6] =  [display.WHITE, display.BLACK, '#', False]
    world.map[23][6] = [0, 1, '.', True]
    world.map[24][6] = [0, 1, '.', True]
    world.map[25][6] = [0, 1, '.', True]
    world.map[26][6] = [0, 1, '.', True]
    world.map[27][6] = [0, 1, '.', True]
    world.map[28][6] =  [display.WHITE, display.BLACK, '#', False]
    world.map[22][7] =  [display.WHITE, display.BLACK, '#', False]
    world.map[23][7] = [0, 1, '.', True]
    world.map[24][7] = [0, 1, '.', True]
    world.map[25][7] = [0, 1, '.', True]
    world.map[26][7] = [0, 1, '.', True]
    world.map[27][7] = [0, 1, '.', True]
    world.map[28][7] =  [display.WHITE, display.BLACK, '#', False]
    world.map[22][8] =  [display.WHITE, display.BLACK, '#', False]
    world.map[23][8] = [0, 1, '.', True]
    world.map[24][8] = [0, 1, '.', True]
    world.map[25][8] = [0, 1, '.', True]
    world.map[26][8] = [0, 1, '.', True]
    world.map[27][8] = [0, 1, '.', True]
    world.map[28][8] =  [display.WHITE, display.BLACK, '#', False]
    world.map[22][9] =  [display.WHITE, display.BLACK, '#', False]
    world.map[23][9] = [0, 1, '.', True]
    world.map[24][9] = [0, 1, '.', True]
    world.map[25][9] = [0, 1, '.', True]
    world.map[26][9] = [0, 1, '.', True]
    world.map[27][9] = [0, 1, '.', True]
    world.map[28][9] =  [display.WHITE, display.BLACK, '#', False]
    world.map[22][10] =  [display.WHITE, display.BLACK, '#', False]
    world.map[23][10] =  [display.WHITE, display.BLACK, '#', False]
    world.map[24][10] =  [display.WHITE, display.BLACK, '#', False]
    world.map[25][10] = [0, 1, '.', True]
    world.map[26][10] =  [display.WHITE, display.BLACK, '#', False]
    world.map[27][10] =  [display.WHITE, display.BLACK, '#', False]
    world.map[28][10] =  [display.WHITE, display.BLACK, '#', False]
    world.map[25][12] = [0, 1, 'W', True]
    world.map[24][13] = [0, 1, 'A', True]
    world.map[25][13] = [0, 1, 'S', True]
    world.map[26][13] = [0, 1, 'D', True]
    world.map[22][14] = [0, 1, 'T', True]
    world.map[23][14] = [0, 1, 'O', True]
    world.map[24][14] = [0, 1, ' ', True]
    world.map[25][14] = [0, 1, 'M', True]
    world.map[26][14] = [0, 1, 'O', True]
    world.map[27][14] = [0, 1, 'V', True]
    world.map[28][14] = [0, 1, 'E', True]
    world.map[22][16] =  [display.BLUE, display.BLACK, 'O', False]
    world.map[23][16] = [0, 1, '=', True]
    world.map[24][16] = [0, 1, 'P', True]
    world.map[25][16] = [0, 1, 'o', True]
    world.map[26][16] = [0, 1, 'r', True]
    world.map[27][16] = [0, 1, 't', True]
    world.map[28][16] = [0, 1, 'a', True]
    world.map[29][16] = [0, 1, 'l', True]
    world.map[19][17] = [0, 1, 'Y', True]
    world.map[20][17] = [0, 1, 'O', True]
    world.map[21][17] = [0, 1, 'U', True]
    world.map[23][17] = [0, 1, '>', True]
    world.map[27][17] = [0, 1, '<', True]
    world.map[29][17] = [0, 1, 'Y', True]
    world.map[30][17] = [0, 1, 'O', True]
    world.map[31][17] = [0, 1, 'U', True]
