# This file automatically generated from a template. That's why it defines the world one at a time instead of using loops
import display
import world

from objects import world_object
from objects import General

class state_thing(world_object.world_object):
    def collide(this, oth):
        if oth.type == "player":
            world.dungeon_state_diff["test_val"] = True

    def color(this):
        if world.dungeon_state["test_val"]:
            return display.GREEN
        return display.RED

    def char(this):
        return "?"

def generate():
    world.objects.clear()

    world.objects.append(General.dungeon_start.dungeon_start(["test_dungeon_1"], {"test_val" : False}))
    world.objects.append(General.portal.portal(20, 10, "warrior_start", 24, 13))
    world.objects.append(General.portal.portal(30, 10, "test_dungeon_1", 10, 10))
    world.objects.append(state_thing(25, 7, "test"))

    world.map = [[[0, 1, ' ', True] for y in range(world.WORLD_Y)] for x in range(world.WORLD_X)]
    world.map[0][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[1][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[2][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[3][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[4][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[5][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[6][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[7][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[8][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[9][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[10][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[11][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[12][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[13][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[14][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[15][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[16][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[17][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[18][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[19][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[20][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[21][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[22][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[23][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[24][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[25][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[26][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[27][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[28][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[29][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[30][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[31][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[32][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[33][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[34][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[35][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[36][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[37][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[38][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[39][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[40][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[41][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[42][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[43][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[44][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[45][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[46][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[47][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[48][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][1] =  [display.WHITE, display.BLACK, '#', False]
    world.map[10][1] = [0, 1, 'T', True]
    world.map[11][1] = [0, 1, 'E', True]
    world.map[12][1] = [0, 1, 'S', True]
    world.map[13][1] = [0, 1, 'T', True]
    world.map[15][1] = [0, 1, 'D', True]
    world.map[16][1] = [0, 1, 'U', True]
    world.map[17][1] = [0, 1, 'N', True]
    world.map[18][1] = [0, 1, 'G', True]
    world.map[19][1] = [0, 1, 'E', True]
    world.map[20][1] = [0, 1, 'O', True]
    world.map[21][1] = [0, 1, 'N', True]
    world.map[25][1] = [0, 1, 'D', True]
    world.map[26][1] = [0, 1, 'E', True]
    world.map[27][1] = [0, 1, 'V', True]
    world.map[28][1] = [0, 1, 'S', True]
    world.map[30][1] = [0, 1, 'O', True]
    world.map[31][1] = [0, 1, 'N', True]
    world.map[32][1] = [0, 1, 'L', True]
    world.map[33][1] = [0, 1, 'Y', True]
    world.map[49][1] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][2] =  [display.WHITE, display.BLACK, '#', False]
    world.map[2][2] = [0, 1, 'P', True]
    world.map[3][2] = [0, 1, 'l', True]
    world.map[4][2] = [0, 1, 'e', True]
    world.map[5][2] = [0, 1, 'a', True]
    world.map[6][2] = [0, 1, 's', True]
    world.map[7][2] = [0, 1, 'e', True]
    world.map[9][2] = [0, 1, 's', True]
    world.map[10][2] = [0, 1, 'u', True]
    world.map[11][2] = [0, 1, 'b', True]
    world.map[12][2] = [0, 1, 'm', True]
    world.map[13][2] = [0, 1, 'i', True]
    world.map[14][2] = [0, 1, 't', True]
    world.map[16][2] = [0, 1, 'a', True]
    world.map[18][2] = [0, 1, 'b', True]
    world.map[19][2] = [0, 1, 'u', True]
    world.map[20][2] = [0, 1, 'g', True]
    world.map[22][2] = [0, 1, 'r', True]
    world.map[23][2] = [0, 1, 'e', True]
    world.map[24][2] = [0, 1, 'p', True]
    world.map[25][2] = [0, 1, 'o', True]
    world.map[26][2] = [0, 1, 'r', True]
    world.map[27][2] = [0, 1, 't', True]
    world.map[29][2] = [0, 1, 'i', True]
    world.map[30][2] = [0, 1, 'f', True]
    world.map[32][2] = [0, 1, 'y', True]
    world.map[33][2] = [0, 1, 'o', True]
    world.map[34][2] = [0, 1, 'u', True]
    world.map[36][2] = [0, 1, 'g', True]
    world.map[37][2] = [0, 1, 'o', True]
    world.map[38][2] = [0, 1, 't', True]
    world.map[40][2] = [0, 1, 'i', True]
    world.map[41][2] = [0, 1, 'n', True]
    world.map[43][2] = [0, 1, 'h', True]
    world.map[44][2] = [0, 1, 'e', True]
    world.map[45][2] = [0, 1, 'r', True]
    world.map[46][2] = [0, 1, 'e', True]
    world.map[49][2] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][3] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][3] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][4] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][4] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][5] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][5] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][6] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][6] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][7] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][7] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][8] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][8] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][9] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][9] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][10] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][10] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][11] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][11] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][12] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][12] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][13] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][13] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][14] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][14] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][15] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][15] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][16] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][16] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][17] =  [display.WHITE, display.BLACK, '#', False]
    world.map[12][17] = [display.RED, 1, 'W', True]
    world.map[13][17] = [display.RED, 1, 'A', True]
    world.map[14][17] = [display.RED, 1, 'R', True]
    world.map[15][17] = [display.RED, 1, 'N', True]
    world.map[16][17] = [display.RED, 1, 'I', True]
    world.map[17][17] = [display.RED, 1, 'N', True]
    world.map[18][17] = [display.RED, 1, 'G', True]
    world.map[19][17] = [display.RED, 1, ':', True]
    world.map[49][17] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][18] =  [display.WHITE, display.BLACK, '#', False]
    world.map[4][18] =  [display.RED, 1, 'G', True]
    world.map[5][18] =  [display.RED, 1, 'O', True]
    world.map[6][18] =  [display.RED, 1, 'I', True]
    world.map[7][18] =  [display.RED, 1, 'N', True]
    world.map[8][18] =  [display.RED, 1, 'G', True]
    world.map[10][18] = [display.RED, 1, 'F', True]
    world.map[11][18] = [display.RED, 1, 'U', True]
    world.map[12][18] = [display.RED, 1, 'R', True]
    world.map[13][18] = [display.RED, 1, 'T', True]
    world.map[14][18] = [display.RED, 1, 'H', True]
    world.map[15][18] = [display.RED, 1, 'E', True]
    world.map[16][18] = [display.RED, 1, 'R', True]
    world.map[18][18] = [display.RED, 1, 'C', True]
    world.map[19][18] = [display.RED, 1, 'A', True]
    world.map[20][18] = [display.RED, 1, 'N', True]
    world.map[22][18] = [display.RED, 1, 'D', True]
    world.map[23][18] = [display.RED, 1, 'E', True]
    world.map[24][18] = [display.RED, 1, 'L', True]
    world.map[25][18] = [display.RED, 1, 'E', True]
    world.map[26][18] = [display.RED, 1, 'T', True]
    world.map[27][18] = [display.RED, 1, 'E', True]
    world.map[29][18] = [display.RED, 1, 'Y', True]
    world.map[30][18] = [display.RED, 1, 'O', True]
    world.map[31][18] = [display.RED, 1, 'U', True]
    world.map[32][18] = [display.RED, 1, 'R', True]
    world.map[34][18] = [display.RED, 1, 'C', True]
    world.map[35][18] = [display.RED, 1, 'H', True]
    world.map[36][18] = [display.RED, 1, 'A', True]
    world.map[37][18] = [display.RED, 1, 'R', True]
    world.map[38][18] = [display.RED, 1, 'A', True]
    world.map[39][18] = [display.RED, 1, 'C', True]
    world.map[40][18] = [display.RED, 1, 'T', True]
    world.map[41][18] = [display.RED, 1, 'E', True]
    world.map[42][18] = [display.RED, 1, 'R', True]
    world.map[49][18] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[1][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[2][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[3][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[4][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[5][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[6][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[7][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[8][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[9][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[10][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[11][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[12][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[13][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[14][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[15][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[16][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[17][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[18][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[19][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[20][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[21][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[22][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[23][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[24][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[25][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[26][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[27][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[28][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[29][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[30][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[31][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[32][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[33][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[34][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[35][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[36][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[37][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[38][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[39][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[40][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[41][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[42][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[43][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[44][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[45][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[46][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[47][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[48][19] =  [display.WHITE, display.BLACK, '#', False]
    world.map[49][19] =  [display.WHITE, display.BLACK, '#', False]
