# This file automatically generated from a template. That's why it defines the world one at a time instead of using loops
import display
import world

from objects import General

def generate():
    world.objects.clear()

    world.objects.append(General.portal.portal(1, 1, "mage_start", 1, 2))
    world.objects.append(General.portal.portal(1, 5, "mage_start", 2, 5))
    world.objects.append(General.portal.portal(41, 15, "mage_start", 41, 14))

    world.map = [[ [display.WHITE, display.BLACK, ' ', True] for y in range(world.WORLD_Y)] for x in range(world.WORLD_X)]
    world.map[0][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[1][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[2][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[3][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[4][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[5][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[6][0] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][1] =  [display.WHITE, display.BLACK, '#', False]
    world.map[1][1] =  [display.GREEN, display.BLACK, '*', True]
    world.map[2][1] =  [display.GREEN, display.BLACK, '*', True]
    world.map[3][1] =  [display.GREEN, display.BLACK, '*', True]
    world.map[4][1] =  [display.GREEN, display.BLACK, '*', True]
    world.map[5][1] =  [display.GREEN, display.BLACK, '*', True]
    world.map[6][1] =  [display.GREEN, display.BLACK, '*', True]
    world.map[7][1] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][2] =  [display.WHITE, display.BLACK, '#', False]
    world.map[1][2] =  [display.GREEN, display.BLACK, '*', True]
    world.map[2][2] =  [display.GREEN, display.BLACK, '*', True]
    world.map[3][2] =  [display.GREEN, display.BLACK, '*', True]
    world.map[4][2] =  [display.GREEN, display.BLACK, '*', True]
    world.map[5][2] =  [display.GREEN, display.BLACK, '*', True]
    world.map[6][2] =  [display.GREEN, display.BLACK, '*', True]
    world.map[7][2] =  [display.GREEN, display.BLACK, '*', True]
    world.map[8][2] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][3] =  [display.WHITE, display.BLACK, '#', False]
    world.map[1][3] =  [display.GREEN, display.BLACK, '*', True]
    world.map[2][3] =  [display.GREEN, display.BLACK, '*', True]
    world.map[3][3] =  [display.GREEN, display.BLACK, '*', True]
    world.map[4][3] =  [display.GREEN, display.BLACK, '*', True]
    world.map[5][3] =  [display.GREEN, display.BLACK, '*', True]
    world.map[6][3] =  [display.GREEN, display.BLACK, '*', True]
    world.map[7][3] =  [display.GREEN, display.BLACK, '*', True]
    world.map[8][3] =  [display.GREEN, display.BLACK, '*', True]
    world.map[9][3] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][4] =  [display.WHITE, display.BLACK, '#', False]
    world.map[1][4] =  [display.GREEN, display.BLACK, '*', True]
    world.map[2][4] =  [display.GREEN, display.BLACK, '*', True]
    world.map[3][4] =  [display.GREEN, display.BLACK, '*', True]
    world.map[4][4] =  [display.GREEN, display.BLACK, '*', True]
    world.map[5][4] =  [display.GREEN, display.BLACK, '*', True]
    world.map[6][4] =  [display.GREEN, display.BLACK, '*', True]
    world.map[7][4] =  [display.GREEN, display.BLACK, '*', True]
    world.map[8][4] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][5] =  [display.WHITE, display.BLACK, '#', False]
    world.map[1][5] =  [display.GREEN, display.BLACK, '*', True]
    world.map[2][5] =  [display.GREEN, display.BLACK, '*', True]
    world.map[3][5] =  [display.GREEN, display.BLACK, '*', True]
    world.map[4][5] =  [display.GREEN, display.BLACK, '*', True]
    world.map[5][5] =  [display.GREEN, display.BLACK, '*', True]
    world.map[6][5] =  [display.GREEN, display.BLACK, '*', True]
    world.map[7][5] =  [display.WHITE, display.BLACK, '#', False]
    world.map[0][6] =  [display.WHITE, display.BLACK, '#', False]
    world.map[1][6] =  [display.WHITE, display.BLACK, '#', False]
    world.map[2][6] =  [display.WHITE, display.BLACK, '#', False]
    world.map[3][6] =  [display.WHITE, display.BLACK, '#', False]
    world.map[4][6] =  [display.WHITE, display.BLACK, '#', False]
    world.map[5][6] =  [display.WHITE, display.BLACK, '#', False]
    world.map[6][6] =  [display.WHITE, display.BLACK, '#', False]
    world.map[34][12] =  [display.WHITE, display.BLACK, '#', False]
    world.map[35][12] =  [display.WHITE, display.BLACK, '#', False]
    world.map[36][12] =  [display.WHITE, display.BLACK, '#', False]
    world.map[37][12] =  [display.WHITE, display.BLACK, '#', False]
    world.map[38][12] =  [display.WHITE, display.BLACK, '#', False]
    world.map[39][12] =  [display.WHITE, display.BLACK, '#', False]
    world.map[32][13] =  [display.WHITE, display.BLACK, '#', False]
    world.map[33][13] =  [display.WHITE, display.BLACK, '#', False]
    world.map[34][13] =  [display.GREEN, display.BLACK, '*', True]
    world.map[35][13] =  [display.GREEN, display.BLACK, '*', True]
    world.map[36][13] =  [display.GREEN, display.BLACK, '*', True]
    world.map[37][13] =  [display.GREEN, display.BLACK, '*', True]
    world.map[38][13] =  [display.GREEN, display.BLACK, '*', True]
    world.map[39][13] =  [display.GREEN, display.BLACK, '*', True]
    world.map[40][13] =  [display.WHITE, display.BLACK, '#', False]
    world.map[41][13] =  [display.WHITE, display.BLACK, '#', False]
    world.map[31][14] =  [display.WHITE, display.BLACK, '#', False]
    world.map[32][14] =  [display.GREEN, display.BLACK, '*', True]
    world.map[33][14] =  [display.GREEN, display.BLACK, '*', True]
    world.map[34][14] =  [display.GREEN, display.BLACK, '*', True]
    world.map[35][14] =  [display.GREEN, display.BLACK, '*', True]
    world.map[36][14] =  [display.GREEN, display.BLACK, '*', True]
    world.map[37][14] =  [display.GREEN, display.BLACK, '*', True]
    world.map[38][14] =  [display.GREEN, display.BLACK, '*', True]
    world.map[39][14] =  [display.GREEN, display.BLACK, '*', True]
    world.map[40][14] =  [display.GREEN, display.BLACK, '*', True]
    world.map[41][14] =  [display.GREEN, display.BLACK, '*', True]
    world.map[42][14] =  [display.WHITE, display.BLACK, '#', False]
    world.map[31][15] =  [display.WHITE, display.BLACK, '#', False]
    world.map[32][15] =  [display.GREEN, display.BLACK, '*', True]
    world.map[33][15] =  [display.GREEN, display.BLACK, '*', True]
    world.map[34][15] =  [display.GREEN, display.BLACK, '*', True]
    world.map[35][15] =  [display.GREEN, display.BLACK, '*', True]
    world.map[36][15] =  [display.GREEN, display.BLACK, '*', True]
    world.map[37][15] =  [display.GREEN, display.BLACK, '*', True]
    world.map[38][15] =  [display.GREEN, display.BLACK, '*', True]
    world.map[39][15] =  [display.GREEN, display.BLACK, '*', True]
    world.map[40][15] =  [display.GREEN, display.BLACK, '*', True]
    world.map[41][15] =  [display.GREEN, display.BLACK, '*', True]
    world.map[42][15] =  [display.WHITE, display.BLACK, '#', False]
    world.map[32][16] =  [display.WHITE, display.BLACK, '#', False]
    world.map[33][16] =  [display.WHITE, display.BLACK, '#', False]
    world.map[34][16] =  [display.GREEN, display.BLACK, '*', True]
    world.map[35][16] =  [display.GREEN, display.BLACK, '*', True]
    world.map[36][16] =  [display.GREEN, display.BLACK, '*', True]
    world.map[37][16] =  [display.GREEN, display.BLACK, '*', True]
    world.map[38][16] =  [display.GREEN, display.BLACK, '*', True]
    world.map[39][16] =  [display.GREEN, display.BLACK, '*', True]
    world.map[40][16] =  [display.WHITE, display.BLACK, '#', False]
    world.map[41][16] =  [display.WHITE, display.BLACK, '#', False]
    world.map[34][17] =  [display.WHITE, display.BLACK, '#', False]
    world.map[35][17] =  [display.WHITE, display.BLACK, '#', False]
    world.map[36][17] =  [display.WHITE, display.BLACK, '#', False]
    world.map[37][17] =  [display.WHITE, display.BLACK, '#', False]
    world.map[38][17] =  [display.WHITE, display.BLACK, '#', False]
    world.map[39][17] =  [display.WHITE, display.BLACK, '#', False]
